project:
  type: website
  output-dir: _site/
  preview:
    watch-inputs: true
  resources: 
    - rezbuild-emperor-tamarin/static/index.html


bibliography: ./bibliography/bibliography.bib
citeproc: true
csl: ./bibliography/apa.csl

website:
  title: "Dimitri Masson"
  favicon: assets/favicon_128_128.ico
  site-url: "https://dhmmasson.github.io"
  navbar:
    logo: assets/favicon_128_128.webp
    toggle-position: right
    right:
      - text: "About"
        href: about.qmd
      - Bibliography.md        
      - icon: github
        href: https://github.com/dhmmasson
      - icon: linkedin
        href: https://www.linkedin.com/in/dimitri-masson-a595612b/
      - icon: ai ai ai-researchgate-square
        href: https://www.researchgate.net/profile/Dimitri-Masson-2
  page-footer:
    left: 
      - text: "© 2024 Dimitri Masson"
    right:
      - text: "Built with Quarto, "
      - text: "Source code available on GitHub"
      - icon: github
        href: https://github.com/dhmmasson/dhmmasson.github.io
  open-graph: 
    locale: en_US
  comments: 
    utterances:
      repo: dhmmasson/dhmmasson.github.io
      label: "💬 comment"
      theme: boxy-light
      issue-term: title

format:
  html:
    theme: 
      light: 
        - litera
        - assets/dhmmasson_light.scss
      # dark:
      #   - litera
      #   - assets/dhmmasson_dark.scss
    css: 
      - styles.css
      - https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css
      - https://cdn.jsdelivr.net/gh/lipis/flag-icons@7.2.3/css/flag-icons.min.css
    email-obfuscation: javascript
    include-after-body: assets/scripts/obsidian-citation.html

